### ISSUE TITLE
run demo.py error

### ISSUE THREAD

**Issue by yyfanxing** [xingyizhou/CenterNet#107]
when i try to run the demo.py , and erros:
panxiang@panxiang:~/zq/centerNet/CenterNet-master/src$ sudo python demo.py ctdet --demo /home/panxiang/zq/centerNet/CenterNet-master/images/17790319373_bd19b24cfc_k.jpg --load_model /home/panxiang/zq/centerNet/CenterNet-master/models/ctdet_coco_dla_2x.pth
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/panxiang/zq/centerNet/CenterNet-master/src/lib/../../exp/ctdet/default
heads {'wh': 2, 'hm': 80, 'reg': 2}
Creating model...
Downloading: "http://dl.yf.io/dla/models/imagenet/dla34-ba72cf86.pth" to /home/panxiang/.torch/models/dla34-ba72cf86.pth

but i put the ctdet_coco_dla_2x.pth to the  ../models/ctdet_coco_dla_2x.pth  ,why i need download the dla34-ba72cf86.pth ,what is this ?

**Comment by xingyizhou** [comment]
It is the ImageNet pretrained model for DLA. you can comment out that line if you are not training the network.

**Comment by LiyiningLynn** [comment]
@xingyizhou 
sorry but I didn't quite get it, what to comment out?

**Comment by lightingstars** [comment]
> @xingyizhou
> sorry but I didn't quite get it, what to comment out?
change pose_dla_dcn.py get_pose_net function "pretrained=False".What is the role of this pretrained model.
in deteail:
search the pose_dla_dcn.py in the CenterNet-master folder 
then search in the py,fianly,change the pretrained to the false.

**Comment by lightingstars** [comment]
> @xingyizhou
> sorry but I didn't quite get it, what to comment out?
change pose_dla_dcn.py get_pose_net function "pretrained=False".
What is the role of this pretrained model

search the py file in the CenterNet-master folder

**Comment by LiyiningLynn** [comment]
Thank you so much for your reply , I actually have solved this by myself,
all the best!

lightingstars <notifications@github.com>于2019年10月14日 周一下午9:34写道：

**Comment by zy23456** [comment]
Excuse me,  commented this line,  I get an error during the test：Drop parameter base.fc.if you see this ......, see fc appear in the load_pretrained_model function in the code, but because of the comment above One line, this function will not be executed, then the trained model can not be used, or if you want to test, you must download the pre-trained dla model？

**Comment by zy23456** [comment]
@xingyizhou
Excuse me, commented this line, I get an error during the test：Drop parameter base.fc.if you see this ......, see fc appear in the load_pretrained_model function in the code, but because of the comment above One line, this function will not be executed, then the trained model can not be used, or if you want to test, you must download the pre-trained dla model？
