### ISSUE TITLE
training 3d model on new data set

### ISSUE THREAD

**Issue by 123alaa** [xingyizhou/CenterNet#122]
Hi @xingyizhou ,
I have new 3d data set (like kitti), i made all the transformation to convert to kitti format, but i have some questions:
1. You feed to the network locations, and rotation_y, but you did not  get these parameters in the output, why? you compute them from alpha and 2d_box, and calib file.

This is a problem for me, since i work with different lidar and different coordinate system, Can i add them to output and this will work? Can you help?

One more issue, may be i feed the rotate_y and alpha to the network in different format (+- pi/2), Is this will work if did the traverse transformation, because I'm consistent.

Thnak's,
Alaa

**Comment by xingyizhou** [comment]
1. We follow [this](https://arxiv.org/abs/1612.00496) to predict alpha, depth and dimension and recover the 3d bbox using ground truth camera calibration. Other settings are not exploited. Feel free to try.
2. It looks good to me.

**Comment by yeyewen** [comment]
@xingyizhou  Hi，I know you follow Deep3Dbox to predict  alpha, depth and dimension and recover the 3d bbox using ground truth camera calibration. Does it mean that you predict 2D box first then train  the 2D box  to predict  alpha, depth and dimension ?My question is that your model to predict 3D is two-stage or one-stage? If one-stage,how to train your model?

**Comment by longbowzhang** [comment]
Hi Guys @yeyewen @123alaa 
I have a similar question here, according to Deep3Dbox, alpha is the local orientation, which will be added to the ray orientation (due to the fact that cropped image are using).
However, this work is an end-to-end one-stage pipeline without any cropping. I am curious that is it necessary to include `np.arctan2(x - cx, fx)` when calculating rot_y as shown in function alpha2rot_y.

Looking forward to your feedback.
Best
