### ISSUE TITLE
how to get the test time 

### ISSUE THREAD

**Issue by sevenseablue** [xingyizhou/CenterNet#15]
```
import sys
CENTERNET_PATH = /path/to/CenterNet/src/lib/
sys.path.insert(0, CENTERNET_PATH)

from detectors.detector_factory import detector_factory
from opts import opts

MODEL_PATH = /path/to/model
TASK = 'ctdet' # or 'multi_pose' for human pose estimation
opt = opts().init('{} --load_model {}'.format(TASK, MODEL_PATH).split(' '))
detector = detector_factory[opt.task](opt)

img_dir = "/home/wangdawei/github/image/CenterNet/images"
import os
import time
t1 = time.time()
for file in os.listdir(img_dir):
    print(file)
    if file.endswith(".jpg"):
        ret = detector.run(img)['results']
        #print(ret)
        pass
print(time.time() - t1)
```

my env:
ubuntu 18.04
gtx 1080 ti
cuda 10.0
pytorch 1.1

i use the code recommend, and the image in the images dir, 10 jpgs,
but i use 0.9 secodes, 90ms per image,  which differs the 19 ms of  the test time

how to get the test time?
is there something wrong with my test?

**Comment by xingyizhou** [comment]
Hi, 
  Can you print the detailed time as in https://github.com/xingyizhou/CenterNet/blob/master/src/demo.py#L31 . The reported 19ms only includes network forwarding time, decoding time, and nms time (not applicable for centernet), as is indicated in the model zoo and following [yolov3](https://github.com/pjreddie/darknet/blob/master/examples/yolo.c#L291) (we move their time to after nms). This is also what we did for reporting the time for other methods. In your case, reading and resizing the image might take a lot of time, since the example images are larger than 512x512. If you really want to speedup the whole pipeline, you can use the multi-thread image pre-processing as in our [testing script](https://github.com/xingyizhou/CenterNet/blob/master/src/test.py#L47) or use other data pre-processing library (e.g. [NIVIDIA-dali](https://github.com/NVIDIA/DALI)) other than opencv for your application.

**Comment by sevenseablue** [comment]
@xingyizhou ， thank you
i print the detailed time like in the demo.py, and i got it. the 90ms is contains the load and pre time, and the first debuger new time, which consume abount 0.5 second.
```
debugger = Debugger(dataset=self.opt.dataset, ipynb=(self.opt.debug==3),
                        theme=self.opt.debugger_theme)
```
the operation net , deocde, post consume  abount 25ms

**Comment by xingyizhou** [comment]
Good. This sounds like a reasonable difference between different machines (on our machine, 1080 Ti runs at 21ms). Also, make sure that you install opencv via `pip install opencv-python`. I observe `conda install opencv` gives a slower version ......

**Comment by xingyizhou** [comment]
Oh the exact time we reported in the paper is measured with `test.py`. `demo.py` also includes visualization time. You can run `python test.py ctdet --load_model ../models/ctdet_coco_dla_2x.pth --keep_res` for a strict re-evaluation.

**Comment by smartwell** [comment]
@xingyizhou thanks for your great work.
win 10.0
pytorch 1.0.3
gtx 1080  ti
cuda 9.0 
cudnn 7.0
my test time：
tot 0.0501s |load 0.0000s |pre 0.0175s |net 0.0286s |dec 0.0020s |post 0.0015s |merge 0.0005s |
tot 0.0506s |load 0.0000s |pre 0.0180s |net 0.0281s |dec 0.0030s |post 0.0015s |merge 0.0000s |
tot 0.0521s |load 0.0000s |pre 0.0180s |net 0.0296s |dec 0.0025s |post 0.0020s |merge 0.0000s |
tot 0.0526s |load 0.0000s |pre 0.0191s |net 0.0291s |dec 0.0025s |post 0.0015s |merge 0.0005s |
tot 0.0501s |load 0.0000s |pre 0.0175s |net 0.0286s |dec 0.0020s |post 0.0015s |merge 0.0005s |
tot 0.0496s |load 0.0000s |pre 0.0175s |net 0.0271s |dec 0.0025s |post 0.0020s |merge 0.0005s |
tot 0.0516s |load 0.0000s |pre 0.0175s |net 0.0291s |dec 0.0030s |post 0.0020s |merge 0.0000s |
tot 0.0491s |load 0.0000s |pre 0.0175s |net 0.0276s |dec 0.0025s |post 0.0015s |merge 0.0000s |
tot 0.0496s |load 0.0000s |pre 0.0170s |net 0.0281s |dec 0.0025s |post 0.0015s |merge 0.0005s |
tot 0.0506s |load 0.0000s |pre 0.0180s |net 0.0281s |dec 0.0025s |post 0.0020s |merge 0.0000s |
