### ISSUE TITLE
 UR CODE WAS COPIED FOR SELL NOW 

### ISSUE THREAD

**Issue by genema** [xingyizhou/CenterNet#19]
http://manaai.cn/aicodes_detail3.html?id=33
A group of contemptible thieves has clone ur code, replace ur license with theirs and peddling it on their "WEBSITE".

**Comment by philkr** [comment]
Thank you for pointing this out. I guess that's how you know you've made it :)
Apart from a change in licensing, there doesn't seem to be anything illegal about this. The MIT license allows for commercial use, even if the authors are not the ones making the money.
I'd obviously recommend everybody to use our code for free, instead of paying someone for it.

Closing this for now, but feel free to reopen if you'd like to discuss this more.
