### ISSUE TITLE
object detection：how to solve objects‘ center points overlap？

### ISSUE THREAD

**Issue by wangleihitcs** [xingyizhou/CenterNet#238]
For object detection，CenterNet has 128 x 128 feature maps for C classes，but has two 128 x 128 feature maps for object width and height. But we do not output 2 x C feature maps for width and height，it is not elegant.
Now I use CenterNet for my detection task，it is useful, but my task exists objects‘ center points overlap. Could you give me some advices，I am a beginner for detection.

**Comment by xingyizhou** [comment]
We don't have a good solution for center collision. You can refer to [this](https://github.com/xingyizhou/CenterNet/blob/master/src/tools/calc_coco_overlap.py) to calculate how often it happens. It will be fewer than you expected. You can also use this script to calculate the IOU overlap to see if you want to switch to FasterRCNN.

**Comment by wangleihitcs** [comment]
> We don't have a good solution for center collision. You can refer to [this](https://github.com/xingyizhou/CenterNet/blob/master/src/tools/calc_coco_overlap.py) to calculate how often it happens. It will be fewer than you expected. You can also use this script to calculate the IOU overlap to see if you want to switch to FasterRCNN.

Thank you very much!

**Comment by mjkvaak** [comment]
An idea that might (or might not) be useful to protect against center collision is to introduce an additional loss to punish the model when the center points get too close. This could help in cases where the objects have a lot of occlusion and CenterNet might tend to produce a smudgy heatmap instead of keeping the center points separated for each object. 

CenterNet resembles Unet - it's a funny consequence that such a loss was actually implemented in the original [Unet paper](https://arxiv.org/pdf/1505.04597.pdf) (see Fig. 3). [Here](https://jaidevd.github.io/posts/weighted-loss-functions-for-instance-segmentation/) is a blog that illustrates the idea well.
