### ISSUE TITLE
Comparing with ExtremeNet and CornerNet

### ISSUE THREAD

**Issue by bsvineethiitg** [xingyizhou/CenterNet#269]
Since COCO hourglass starts with pretrained ExtremeNet weights which was in turn pretrained on CornerNet weights, is it fair to compare CenterNet to those models? Because effectively, CenterNet is trained for a lot more epochs when you include the epochs that went into the pretraining.

Also, can you point me to the pretrained weights that you used for training the hourglass model on COCO? Thanks.

**Comment by bsvineethiitg** [comment]
One more query: Were the pretrained ExtremeNet weights you used to initialize Hourglass for COCO trained originally with channels in RGB order (like other pytorch pretrained models) or BGR? Thanks.

**Comment by DeeperDeeper** [comment]
@bsvineethiitg did you check also this L1loss
 https://github.com/xingyizhou/CenterNet/blob/a5a0483beb0f9e8705f6dc67d8817275369cfa7e/src/lib/models/losses.py#L184. 
Here they average on the all pixels (128^2) but in the paper, they average on the non-zeros pixels!

**Comment by xingyizhou** [comment]
Thanks for the question. This turns out to be the major reason for this work being rejected. CenterNet training from scratch (100epochs) gives `38.9/ 40.6/ 43.0` for `N.A./ flip/ multi scale`. It is not all better than ExtremeNet (100epochs) `35.8/ 40.2/ 43.7`. 
In another perspective, finetuning ExtremeNet from the ExtremeNet (100epochs) pretraining improves ExtremeNet to `36.9/ 41.1/ 44.6`, it also does worse than CenterNet in the same setting `40.9 / 42.8/ 45.7`. 
The CenterNet in the paper (`40.3 / 42.2 / 45.1`) is finetuned from ExtremeNet (50epochs) + CornerNet (~200epochs). We later observed that directly finetuning from ExtremeNet (100epochs) is better than that (`40.9 / 42.8/ 45.7`).
The ExtremeNet (100epochs) is in our [model zoo](https://drive.google.com/drive/u/1/folders/1px-Xg7jXSC79QqgsD1AAGJQkuf5m0zh_).
The models are all trained in BGR.

**Comment by bsvineethiitg** [comment]
> Thanks for the question. This turns out to be the major reason for this work being rejected. CenterNet training from scratch (100epochs) gives `38.9/ 40.6/ 43.0` for `N.A./ flip/ multi scale`. It is not all better than ExtremeNet (100epochs) `35.8/ 40.2/ 43.7`.

By "scratch" you mean ImageNet weights for Hourglass, right?

**Comment by chenyuntc** [comment]
Centernet is my favourite detector. It's ridiculous to reject it for this reason.

**Comment by xingyizhou** [comment]
Thanks @chenyuntc ! This means a lot to us.

**Comment by xingyizhou** [comment]
@bsvineethiitg "scratch" means using random initialization.

**Comment by bsvineethiitg** [comment]
Hi @xingyizhou . Quick clarification please.

So, the model for COCO-HG you reported on the paper (40.3 / 42.2 / 45.1), you said that was finetuned from ExtremeNet (50epochs) + CornerNet (~200epochs).

I want to reproduce that.

Which pretrained model should I use for this? Is it "ExtremeNet_500000.pth"? I'm confused because you referred to that as the 100 epoch ExtremeNet model in your above comment.

Is ExtremeNet_500000.pth the 100 epoch ExtremeNet model or (50 epoch ExtremeNet starting from CornerNet 200 epoch) model?

**Comment by xingyizhou** [comment]
You are correct. `ExtremeNet_500000.pth` is the 100epoch model. The 50-epoch model [ExtremeNet_250000.pth](https://drive.google.com/file/d/1re-A74WRvuhE528X6sWsg1eEbMG8dmE4/view) is in the ExtremeNet repo.

**Comment by wxiaoning** [comment]
> If you have trained your model on the 100 epoch ExtremeNet using the following command (with the same LR and #gpus and batch sizes):
> 
> python main.py ctdet --exp_id coco_hg --arch hourglass --batch_size 24 --master_batch 4 --lr 2.5e-4 --load_model ../models/ExtremeNet_500000.pth --gpus 0,1,2,3,4 --num_epochs 50 --lr_step 40
> 
> could you please share it in the google drive please? Also, I'd be glad if you can confirm if you trained that exactly with above command.

Hello bsvineethiitg, have you tried this command? And can you reproduce the result?
