### ISSUE TITLE
Is the get_dataset function complete?

### ISSUE THREAD

**Issue by mjanddy** [xingyizhou/CenterNet#32]
In the  dataset_factory.py, I found get_dataset is this:
def get_dataset(dataset, task):
  class Dataset(dataset_factory[dataset], _sample_factory[task]):
    pass
  return Dataset
it is right?
when i run code,Iget error:
Traceback (most recent call last):
  File "main.py", line 103, in <module>
    main(opt)
  File "main.py", line 23, in main
    Dataset = get_dataset(opt.dataset, opt.task)
TypeError: get_dataset() missing 1 required positional argument: 'dataset_dir'

**Comment by xingyizhou** [comment]
It is right. https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/dataset_factory.py#L31 `get_dataset` does not require `dataset_dir` if you haven't changed the code.

**Comment by xxy90** [comment]
I also get the same problem. would you like to share that how  you solve this problem? Thank you!

**Comment by MaxBareiss** [comment]
This issue is caused by a conflict with the tensorflow research repository, and their recommendations for changing your `$PYTHONPATH`. If you have a line like this in your `~/.bashrc` or `~/.zshrc`, remove it, restart the shell, and this code will start working:

```bash
export PYTHONPATH=~/git/models/research:~/git/models/research/slim
```

I found this issue by adding this line above [main.py line 22](https://github.com/xingyizhou/CenterNet/blob/master/src/main.py#L22):

```python
import inspect
print(inspect.getmodule(get_dataset).__file__)
```
