### ISSUE TITLE
Huge gap between IOU=0.5 and 0.7 in Kitti

### ISSUE THREAD

**Issue by kaixinbear** [xingyizhou/CenterNet#638]
Hi,xingyi~
I am training your provided code in kitti dataset using the backbone resnet18 with the command:
`python main.py ddd --exp_id 3dop --dataset kitti --kitti_split 3dop --batch_size 16 --master_batch 9 --num_epochs 70 --lr_step 45,60 --gpus 1,2 --arch res_18`
Then I test with `python test.py ddd --exp_id 3dop --dataset kitti --kitti_split 3dop --resume --arch res_18`
I get
![L7W52)8X1$O)24F0M41HEOE](https://user-images.githubusercontent.com/33575107/76142470-19fd6d80-60a9-11ea-8228-af3814c84f3f.png)
It went well until I found that the evaluating code using the iou=0.5.
Then I made the IOU to 0.7 without modifying any place except:
![Y6K%DS_G~{MNIWM JV3KF4N](https://user-images.githubusercontent.com/33575107/76142501-6cd72500-60a9-11ea-8a47-6aa6a5768b24.png)
Then the things turns out to be worse:
![A$IS66B66C_EB}$U903PIR2](https://user-images.githubusercontent.com/33575107/76142504-7fe9f500-60a9-11ea-8310-8669bcc98e0d.png)
The result is so low that it's a little bit strange.Can you please tell me what I did wrong or result is exactly such low?

**Comment by xingyizhou** [comment]
Thank you for raising this up. It is expected that IoU 0.7 << IoU 0.5 for the in-accurate depth prediction. One problem we noted in our 3D detection pipeline is that the 3D bounding box center is not the same as 2D bounding box center due to perspective projection. We had a fixed version that improved the 3D performance a lot. We will release this in the next revision (in > 1 month).

**Comment by kaixinbear** [comment]
Looking forward to your new version!Thx for reply.

**Comment by vobecant** [comment]
Dear @xingyizhou , is this new version, that should improve the KITTI 3D detection in the stricter IoU setup, available somewhere? Thanks!
