### ISSUE TITLE
Paper Publication ??

### ISSUE THREAD

**Issue by lxtGH** [xingyizhou/CenterNet#676]
It is a very amazing and insteresting paper and has huge impact.
there are many follow-up paper and repos. 
But I didn't find the publication information of this paper and I don't know why this paper has not published. 
@xingyizhou 
Thanks!

**Comment by xingyizhou** [comment]
Thank you for liking our paper. Unfortunately, the paper does have been rejected twice. I am super upset about that.

**Comment by lxtGH** [comment]
Thanks for your reply!! Best wish for this paper!

**Comment by ckcraig01** [comment]
Dear Author, Thank you so much for the efforts. Best wishes too

**Comment by bsvineethiitg** [comment]
This is so much great work, @xingyizhou ! I am sorry that the paper has not been published yet... I have one point as feedback, if it helps: the method is not really anchor-free because you use a larger output resolution and effectively still use 1 anchor to detect. This is the reason you can only detect up to 1 object at an output pixel per class. If you had used only keypoint detection (like CornerNet etc) also for estimating the bbox sizes (instead of regression), then this could have been called "anchor-free."

**Comment by bsvineethiitg** [comment]
Are you still trying to publish this work?
