### ISSUE TITLE
Questions about focal loss for heatmap

### ISSUE THREAD

**Issue by shch1210** [xingyizhou/CenterNet#728]
Thanks for your sharing. 

I am confused with heatmap loss. The center of object is 1, after inserting the object into heatmap using gaussian kernel. The value of heat map varies from 0 to 1 in whole heatmap. 

Here is one example：
Assuming ground truth hm_true=[1, 0.2, 0, 0] and predict hm_p=hm_true. The focal loss would not be 0. But if hm_p=[1,0,0,0], the focal loss would be 0.
It is weird when network predicts the desired ground truth but the loss is larger than one other prediction. 

Why don't we directly set the heatmap as only the center point is 1. 

Thanks for your time.

**Comment by xingyizhou** [comment]
That's a really good question. The only one positive version is experimented in the CornerNet paper, and they show using a Gaissuan heatmap brings a nice improvement. It makes a lot of sense to me because this makes the output smooth and easier to model in a convolutional structure. The name "ground truth heatmap" is not accurate, it is more a weight map.

**Comment by shch1210** [comment]
Thanks for your quick reply. 
I understand your explanation. but it is still weird. 
it seems that weighted focal loss in this scenario can not reflect the real loss. But it still works.

**Comment by tengerye** [comment]
@shch1210 Hi, I think because model is harder to learn one point (the center) than a heatmap. Even if the predicted heatmap is not perfect, we can still obtain some points as centers (maybe not exact one). If we predict only one point, if it is missed, we end with nothing. May I ask have you done experiments with prediction the center only? @xingyizhou
